# Workflow name
name: image_to_text_bot_workflow

# Start testing on push and pull_request
on: [push, pull_request]

# Testing jobs
jobs:

  # Testing builds
  build:

    # Testing program on
    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    # Steps
    steps:
      # Add checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # Start testing
      - name: Test
        run: |
          pip install -r requirements.txt
          python test_all.py
